sass:
  sass_dir: _sass

lang: ru
locale: "ru-RU"

remote-theme: pages-themes/hacker

permalink: /:title/

title: "Circiter's blog"
tagline: "Коллекция проектов, мыслей, идей."
description: "Simple technical blog on programming, mathematics, ham-practice, electronics, and recreational science"
baseurl: /

name: "Michael I. Nikitin"
url: "http://circiter.tk"
email: "mailto:xcirciter@gmail.com"

author:
  name: "Michael I. Nikitin"
  github: "https://github.com/Circiter"

github_username: Circiter

github:
  repo: "https://github.com/Circiter/circiter.github.io"

footer-links:
  email: "mailto:xcirciter@gmail.com"
  github: Circiter
  rss: feed.xml

repository: "Circiter/circiter.github.io"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: false
  hard_wrap: false
  math_engine: nil

#plugins_dir: _plugins

#plugins:
#  - jekyll-paginate
#    - liquid_latex

#gems:
#  - jekyll
#  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-paginate
#  - jekyll-latex
#  - liquid_latex
#  - html-proofer

# N.B., texlive & imagemagick are required.
liquid_latex:
  debug: false
  density: 300
  #usepackages: pgf-tikz
  output_directory: /latex
  latex_cmd: "latex -interaction=nonstopmode $texfile &> /dev/null"
  dvips_cmd: "dvips -E $dvifile -o $epsfile &> /dev/null"
  convert_cmd: "convert -density $density $epsfile $pngfile &> /dev/null"
  temp_filename: "latex_temp"

encoding: "UTF-8"

exclude: [Gemfile, Dockerfile, build.sh, action.yml]

collections:
  blog_posts:
    output: true
    permalink: /:collection/:path/
