sass:
  sass_dir: _sass

lang: ru
locale: "ru-RU"

future: true
year: 2020

remote-theme: pages-themes/hacker

permalink: /:title/

title: "Circiter's blog"
tagline: "Коллекция проектов, мыслей, идей."
description: "Simple technical blog on programming, mathematics, ham-practice, electronics, and recreational science"
baseurl: /

name: "Michael I. Nikitin"
url: "http://circiter.tk"
email: "mailto:xcirciter@gmail.com"

author:
  name: "Michael I. Nikitin"
  github: "https://github.com/Circiter"

github_username: Circiter

github:
  repo: "https://github.com/Circiter/circiter.github.io"

footer-links:
  email: "mailto:xcirciter@gmail.com"
  github: Circiter
  rss: feed.xml

repository: "Circiter/circiter.github.io"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: false
  hard_wrap: false
  #math_engine: +nil+
  math_engine: simplemath

plugins_dir: _plugins

plugins:
  #- jekyll-paginate
  #- liquid_latex
  - jekyll-sitemap
  - jekyll-feed
  #- jekyll-latex
  - jekyll/scholar
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll_inline_highlight
  #- jekyll-default-layout

optional_front_matter:
  remove_originals: true

titles_from_headings:
  strip_title: true
  collection: true

# N.B., texlive & imagemagick are required.
liquid_latex:
  debug: true
  density: 200
  #usepackages: babel
  #usepackages: pgf-tikz
  #output_directory: /latex
  latex_cmd: "latex -interaction=nonstopmode $texfile"
  dvips_cmd: "dvips -E $dvifile -o $epsfile"
  convert_cmd: "convert -density $density $epsfile $pngfile"
  temp_filename: "latex_temp"

encoding: "UTF-8"

exclude: [Gemfile, Gemfile.lock, .github, .gitignore, .gemrc]

collections:
  blog_posts:
    output: true
    permalink: /:collection/:path/
