sass:
  sass_dir: _sass

lang: ru
locale: "ru-RU"

future: true
year: 2020

#remote-theme: pages-themes/hyde

permalink: /:title

title: "Дневник Circiter'а"
tagline: "Коллекция проектов, мыслей, идей."
description: "Технический блог о программировании, математике, радиолюбительской практике, электронике и занимательной науке."
baseurl: /

name: "Michael I. Nikitin"
url: "http://circiter.tk"
email: "mailto:xcirciter@gmail.com"

author:
  name: "Michael I. Nikitin"
  github: "https://github.com/Circiter"

github_username: Circiter

github:
  repo: "https://github.com/Circiter/circiter.github.io"

footer-links:
  email: "mailto:xcirciter@gmail.com"
  github: Circiter
  rss: rss.xml

repository: "Circiter/circiter.github.io"

markdown: kramdown

kramdown:
  #input: GFM
  input: KramdownEasyLink
  syntax_highlighter: rouge
  #syntax_highligher: coderay
  #auto_ids: true
  #auto_id_stripping
  #transliterated_header_ids
  #gfm_quirks:
  hard_wrap: false
  math_engine: simplemath

  #syntax_highlighter_opts:
  #  wrap: div
  #  line_number: nil
  #  tab_width: 4
  #  bold_every: 10
  #  css: class

plugins_dir: _plugins

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll/scholar
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll_inline_highlight
  - jekyll-toc
  #- jekyll-default-layout

scholar:
  style: mla
  locale: ru
  source: ./_bibliography
  bibliography: bibliography.bib

optional_front_matter:
  remove_originals: true

titles_from_headings:
  strip_title: true
  collection: true

encoding: "UTF-8"

include: [eq, public]
exclude: [Gemfile, Gemfile.lock, .github, .gitignore, .gemrc]

collections:
  blog_posts:
    output: true
    permalink: /:path
