sass:
  sass_dir: _sass

lang: ru
locale: "ru-RU"

future: true
year: 2020

permalink: /:title

title: "Дневник Circiter'а"
tagline: "Коллекция проектов, мыслей, идей."
description: "Технический блог о программировании, математике, радиолюбительской практике, электронике и занимательной науке."
baseurl: /

name: "Michael I. Nikitin"
url: "http://circiter.tk"
email: "mailto:xcirciter@gmail.com"

author:
  name: "Michael I. Nikitin"
  github: "https://github.com/Circiter"

github_username: Circiter

github:
  repo: "https://github.com/Circiter/circiter.github.io"

footer-links:
  email: "mailto:xcirciter@gmail.com"
  github: Circiter
  rss: rss.xml

repository: "Circiter/circiter.github.io"

#markdown: kramdown
#markdown: redcarpet
markdown: CommonMarkGhPages
#markdown: CommonMark

commonmark:
  # UNSAFE
  # LIBERAL_HTML_TAG

  #options: ["UNSAFE", "SMART", "FOOTNOTES", "STRIKETHROUGH_DOUBLE_TILDE"]
  options: ["SMART", "FOOTNOTES", "STRIKETHROUGH_DOUBLE_TILDE"]

  #autolink
  extensions: ["strikethrough", "table"]

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "fenced_code_blocks", "disable_indented_code_blocks", "lax_spacing", "space_after_headers", "footnotes", "xhtml", "smart"]

kramdown:
  input: GFM
  #input: KramdownEasyLink
  syntax_highlighter: rouge
  #syntax_highligher: coderay
  auto_ids: true
  #auto_id_stripping
  transliterated_header_ids: true
  gfm_quirks: paragraph_end
  hard_wrap: false
  math_engine: simplemath
  #math_engine: nil
  #parse_block_html: true

  syntax_highlighter_opts:
    default_lang: plaintext
  #  wrap: div
  #  line_number: nil
  #  tab_width: 4
  #  bold_every: 10
  #  css: class

plugins_dir: _plugins

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll_inline_highlight
  - jekyll-toc

scholar:
  #style: apa
  #style: ./_bibliography/ieee-with-url.csl
  #style: modern-language-association
  #style: elsevier-vancouver
  #style: elsevier-harvard
  #style: gost-r-7-0-5-2008-numeric

  #style: ./_bibliography/ieee-with-url.csl
  #style: _bibliography/gost-r-7-0-5-2008-numeric.csl
  style: _bibliography/gost-customized.csl
  #style: ieee-with-url
  bibliography_list_tag: ul
  locale: ru
  source: ./_bibliography
  #bibliography: bibliography.bib
  bibliography: "**/*.bib"
  bibtex_filter:
    latex
    markdown

optional_front_matter:
  remove_originals: true

titles_from_headings:
  strip_title: true
  collection: true

encoding: "UTF-8"

include: [eq, public, comments, sig, staticman.yml]
exclude: [Gemfile, Gemfile.lock, .github, .gitignore, .gemrc]

collections:
  blog_posts:
    output: true
    permalink: /:path
