sass:
  sass_dir: _sass

lang: ru
locale: "ru-RU"

future: true
year: 2020

#remote-theme: pages-themes/hyde

#permalink: /:title/
permalink: /:title

title: "Дневник Circiter'а"
tagline: "Коллекция проектов, мыслей, идей."
description: "Технический блог о программировании, математике, радиолюбительской практике, электронике и занимательной науке."
baseurl: /

name: "Michael I. Nikitin"
url: "http://circiter.tk"
email: "mailto:xcirciter@gmail.com"

author:
  name: "Michael I. Nikitin"
  github: "https://github.com/Circiter"

github_username: Circiter

github:
  repo: "https://github.com/Circiter/circiter.github.io"

footer-links:
  email: "mailto:xcirciter@gmail.com"
  github: Circiter
  rss: rss.xml

repository: "Circiter/circiter.github.io"

markdown: kramdown
#highlighter: rouge
highlighter: pygments

kramdown:
  #input: GFM
  input: KramdownEasyLink
  #syntax_highlighter: rouge
  enable_coderay: true
  #syntax_highlighter: pygments
  # Try coderay, pygments.
  #auto_ids: false
  hard_wrap: false
  #math_engine: +nil+
  math_engine: simplemath

  coderay:
      coderay_wrap: div
      coderay_line_number: nil
      #coderay_tab_width: 4
      #coderay_bold_every: 10
      coderay_css: class

plugins_dir: _plugins

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll/scholar
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll_inline_highlight
  #- jekyll-default-layout

scholar:
  style: mla
  locale: ru
  source: ./_bibliography
  bibliography: bibliography.bib

optional_front_matter:
  remove_originals: true

titles_from_headings:
  strip_title: true
  collection: true

encoding: "UTF-8"

include: [eq, public]
exclude: [Gemfile, Gemfile.lock, .github, .gitignore, .gemrc]

collections:
  blog_posts:
    output: true
    #permalink: /:collection/:path/
    permalink: /:path
