name: build-blog-workflow

on:
  push:
    branches:
      - source

jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    #- name: Cache some files
    #  uses: actions/cache@v1
    #  with:
    #    path: ~/.npm
    #    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #    restore-keys: |
    #      ${{ runner.os }}-build-${{ env.cache-name }}-
    #      ${{ runner.os }}-build-
    #      ${{ runner.os }}-

    - name: Build jekyll site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: source
        BRANCH: master
        CNAME: circiter.tk
        FOLDER: _site
      uses: ./.github/actions/build-blog-action

    - name: Trying to update the web site
      uses: actions/github-script@0.4.0
      with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.updateFile({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: "./empty_file",
              message: "Trying to update the web site",
              content: ""
            })
