name: GitHub Pages deploy

on:
  push:
    branches:
      - source

jobs:
  checkout-and-deploy:
    env:
      FOLDER: _site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    #- name: Creating destination folder
      # Create the destination folder now to prevent
      # the "permission denied" error later.
      #run: mkdir $FOLDER

    - name: Build jekyll site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: source
        BRANCH: master
        CNAME: circiter.tk
      uses: ./
